# Generated by Django 4.2.1 on 2023-05-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_tag_like_comment_article_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='blog',
            new_name='article',
        ),
    ]
